### ISSUE TITLE
Chris asks you to test GitHub replies :-)

### ISSUE THREAD

**Issue by chartgerink** [chartgerink/dissertation#5]
Hi Marcel (@Sjakie37) and Jelte (@Wicherts),

Just testing the commenting stuff. Hit reply in your email and subsequently type whatever and hit send. Let's agree to keep this in english so others can enjoy our discussions? (these are public mind you :100:)

Cheers,
Chris

**Comment by chartgerink** [comment]
@Wicherts does this work for you?

**Comment by Wicherts** [comment]
Does it? Me think it does!

Sent from my iPhone

On 8 Dec 2017, at 13:24, Chris Hartgerink <notifications@github.com<mailto:notifications@github.com>> wrote:


@Wicherts<https://github.com/wicherts> does this work for you?

**Comment by Sjakie37** [comment]
Yo guys, have a nice weekend and see you on Monday
Marcel

Op 7 dec. 2017 om 16:23 heeft Chris Hartgerink <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi Marcel (@Sjakie37<https://github.com/sjakie37>) and Jelte (@Wicherts<https://github.com/wicherts>),

Just testing the commenting stuff. Hit reply in your email and subsequently type whatever and hit send. Let's agree to keep this in english so others can enjoy our discussions? (these are public mind you 💯)

Cheers,
Chris
