### ISSUE TITLE
Added your repo to my list-of-phd-repos

### ISSUE THREAD

**Issue by Bubblbu** [chartgerink/dissertation#7]
Hi Chris,

I am collecting various examples of repositories about PhD projects and theses on GitHub. Hope it's okay if I add this one to the list as it's a pretty cool example of ongoing progress tracking and outlinking to publications etc.

https://github.com/Bubblbu/list-of-phd-repos

**Comment by chartgerink** [comment]
Sure, no problem! I am expected to hand in my dissertation by August at the latest so this will develop further :)
